root = "${HOME}/.local/share/nvim/site/pack/rafik/opt"
lockfile = "${HOME}/.local/share/nvim/plugins.lock.toml"

repos = [
  "https://github.com/akinsho/toggleterm.nvim",
  "https://github.com/bfredl/nvim-miniyank",
  "https://github.com/dcampos/nvim-snippy",
  "https://github.com/dstein64/vim-startuptime",
  "https://github.com/echasnovski/mini.nvim",
  "https://github.com/ibhagwan/fzf-lua",
  "https://github.com/leoluz/nvim-dap-go",
  "https://github.com/ludovicchabant/vim-gutentags",
  "https://github.com/lukas-reineke/lsp-format.nvim",
  "https://github.com/mfussenegger/nvim-dap",
  "https://github.com/mtdl9/vim-log-highlighting",
  "https://github.com/neovim/nvim-lspconfig",
  "https://github.com/nvim-treesitter/nvim-treesitter",
  "https://github.com/nvim-treesitter/nvim-treesitter-refactor",
  "https://github.com/nvim-treesitter/nvim-treesitter-textobjects",
  "https://github.com/phelipetls/jsonpath.nvim",
  "https://github.com/rafikdraoui/couleurs.vim",
  "https://github.com/rafikdraoui/jj-diffconflicts",
  "https://github.com/rbong/vim-buffest",
  "https://github.com/rhysd/git-messenger.vim",
  "https://github.com/romainl/vim-qf",
  "https://github.com/simnalamburt/vim-mundo",
  "https://github.com/svermeulen/vim-subversive",
  "https://github.com/terrastruct/d2-vim",
  "https://github.com/tpope/vim-characterize",
  "https://github.com/tpope/vim-eunuch",
  "https://github.com/tpope/vim-projectionist",
  "https://github.com/tpope/vim-repeat",
  "https://github.com/tpope/vim-rsi",
  "https://github.com/tpope/vim-scriptease",
  "https://github.com/vim-test/vim-test",
  "https://github.com/whiteinge/diffconflicts",
]
